FROM alpine:latest as cert-img
RUN  apk --no-cache add ca-certificates

FROM scratch
ADD  rootfs.tar /
WORKDIR /etc/ssl/certs
COPY --from=cert-img /etc/ssl/certs/* ./

WORKDIR /var
RUN  [ "/usr/bin/curl", "https://sh.rustup.rs", "-o", "rustup.sh" ]
RUN  [ "/bin/ash", "rustup.sh", "-y"]
